# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='raft.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nraft.proto\"^\n\x0eRequestVoteRPC\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"4\n\x0fResponseVoteRPC\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"\x94\x01\n\x17RequestAppendEntriesRPC\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x18\n\x05\x65ntry\x18\x05 \x01(\x0b\x32\t.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"9\n\x18ResponseAppendEntriesRPC\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\")\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"\x19\n\nLogMessage\x12\x0b\n\x03log\x18\x01 \x01(\t\"\x18\n\x16RequestListMessagesRPC\"4\n\x17ResponseListMessagesRPC\x12\x19\n\x04logs\x18\x01 \x03(\x0b\x32\x0b.LogMessage2\xc0\x01\n\x04Raft\x12+\n\x04Vote\x12\x0f.RequestVoteRPC\x1a\x10.ResponseVoteRPC\"\x00\x12\x46\n\rAppendMessage\x12\x18.RequestAppendEntriesRPC\x1a\x19.ResponseAppendEntriesRPC\"\x00\x12\x43\n\x0cListMessages\x12\x17.RequestListMessagesRPC\x1a\x18.ResponseListMessagesRPC\"\x00\x62\x06proto3'
)




_REQUESTVOTERPC = _descriptor.Descriptor(
  name='RequestVoteRPC',
  full_name='RequestVoteRPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='RequestVoteRPC.term', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='candidateId', full_name='RequestVoteRPC.candidateId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastLogIndex', full_name='RequestVoteRPC.lastLogIndex', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastLogTerm', full_name='RequestVoteRPC.lastLogTerm', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=108,
)


_RESPONSEVOTERPC = _descriptor.Descriptor(
  name='ResponseVoteRPC',
  full_name='ResponseVoteRPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='ResponseVoteRPC.term', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voteGranted', full_name='ResponseVoteRPC.voteGranted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=162,
)


_REQUESTAPPENDENTRIESRPC = _descriptor.Descriptor(
  name='RequestAppendEntriesRPC',
  full_name='RequestAppendEntriesRPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='RequestAppendEntriesRPC.term', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leaderId', full_name='RequestAppendEntriesRPC.leaderId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prevLogIndex', full_name='RequestAppendEntriesRPC.prevLogIndex', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prevLogTerm', full_name='RequestAppendEntriesRPC.prevLogTerm', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entry', full_name='RequestAppendEntriesRPC.entry', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leaderCommit', full_name='RequestAppendEntriesRPC.leaderCommit', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=313,
)


_RESPONSEAPPENDENTRIESRPC = _descriptor.Descriptor(
  name='ResponseAppendEntriesRPC',
  full_name='ResponseAppendEntriesRPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='ResponseAppendEntriesRPC.term', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='ResponseAppendEntriesRPC.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=372,
)


_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='LogEntry.term', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='LogEntry.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=415,
)


_LOGMESSAGE = _descriptor.Descriptor(
  name='LogMessage',
  full_name='LogMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='LogMessage.log', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=442,
)


_REQUESTLISTMESSAGESRPC = _descriptor.Descriptor(
  name='RequestListMessagesRPC',
  full_name='RequestListMessagesRPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=468,
)


_RESPONSELISTMESSAGESRPC = _descriptor.Descriptor(
  name='ResponseListMessagesRPC',
  full_name='ResponseListMessagesRPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='logs', full_name='ResponseListMessagesRPC.logs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=522,
)

_REQUESTAPPENDENTRIESRPC.fields_by_name['entry'].message_type = _LOGENTRY
_RESPONSELISTMESSAGESRPC.fields_by_name['logs'].message_type = _LOGMESSAGE
DESCRIPTOR.message_types_by_name['RequestVoteRPC'] = _REQUESTVOTERPC
DESCRIPTOR.message_types_by_name['ResponseVoteRPC'] = _RESPONSEVOTERPC
DESCRIPTOR.message_types_by_name['RequestAppendEntriesRPC'] = _REQUESTAPPENDENTRIESRPC
DESCRIPTOR.message_types_by_name['ResponseAppendEntriesRPC'] = _RESPONSEAPPENDENTRIESRPC
DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY
DESCRIPTOR.message_types_by_name['LogMessage'] = _LOGMESSAGE
DESCRIPTOR.message_types_by_name['RequestListMessagesRPC'] = _REQUESTLISTMESSAGESRPC
DESCRIPTOR.message_types_by_name['ResponseListMessagesRPC'] = _RESPONSELISTMESSAGESRPC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestVoteRPC = _reflection.GeneratedProtocolMessageType('RequestVoteRPC', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTERPC,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:RequestVoteRPC)
  })
_sym_db.RegisterMessage(RequestVoteRPC)

ResponseVoteRPC = _reflection.GeneratedProtocolMessageType('ResponseVoteRPC', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEVOTERPC,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:ResponseVoteRPC)
  })
_sym_db.RegisterMessage(ResponseVoteRPC)

RequestAppendEntriesRPC = _reflection.GeneratedProtocolMessageType('RequestAppendEntriesRPC', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTAPPENDENTRIESRPC,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:RequestAppendEntriesRPC)
  })
_sym_db.RegisterMessage(RequestAppendEntriesRPC)

ResponseAppendEntriesRPC = _reflection.GeneratedProtocolMessageType('ResponseAppendEntriesRPC', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEAPPENDENTRIESRPC,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:ResponseAppendEntriesRPC)
  })
_sym_db.RegisterMessage(ResponseAppendEntriesRPC)

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), {
  'DESCRIPTOR' : _LOGENTRY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:LogEntry)
  })
_sym_db.RegisterMessage(LogEntry)

LogMessage = _reflection.GeneratedProtocolMessageType('LogMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOGMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:LogMessage)
  })
_sym_db.RegisterMessage(LogMessage)

RequestListMessagesRPC = _reflection.GeneratedProtocolMessageType('RequestListMessagesRPC', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTLISTMESSAGESRPC,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:RequestListMessagesRPC)
  })
_sym_db.RegisterMessage(RequestListMessagesRPC)

ResponseListMessagesRPC = _reflection.GeneratedProtocolMessageType('ResponseListMessagesRPC', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSELISTMESSAGESRPC,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:ResponseListMessagesRPC)
  })
_sym_db.RegisterMessage(ResponseListMessagesRPC)



_RAFT = _descriptor.ServiceDescriptor(
  name='Raft',
  full_name='Raft',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=525,
  serialized_end=717,
  methods=[
  _descriptor.MethodDescriptor(
    name='Vote',
    full_name='Raft.Vote',
    index=0,
    containing_service=None,
    input_type=_REQUESTVOTERPC,
    output_type=_RESPONSEVOTERPC,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AppendMessage',
    full_name='Raft.AppendMessage',
    index=1,
    containing_service=None,
    input_type=_REQUESTAPPENDENTRIESRPC,
    output_type=_RESPONSEAPPENDENTRIESRPC,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListMessages',
    full_name='Raft.ListMessages',
    index=2,
    containing_service=None,
    input_type=_REQUESTLISTMESSAGESRPC,
    output_type=_RESPONSELISTMESSAGESRPC,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RAFT)

DESCRIPTOR.services_by_name['Raft'] = _RAFT

# @@protoc_insertion_point(module_scope)
